elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.192-168-1-224.nip.io"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &host chat.192-168-1-224.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *host
  config:
    default:
      base_url: https://matrix.192-168-1-224.nip.io
      server_name: 192-168-1-224.nip.io
